name: 🧪 test

on:
    push:
        branches: [ dev ]
    pull_request:
        branches: [ dev ]
    workflow_dispatch:

jobs:
    build:
        name: Test
        strategy:
            matrix:
                go-version: [1.19.x]
                os: [ubuntu-latest, windows-latest, macOS-12]
        runs-on: ${{ matrix.os }}
        steps:
            -
                name: Set up Go
                uses: actions/setup-go@v3
                with:
                    go-version: ${{ matrix.go-version }}
            -
                name: Checkout the code
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0
            - 
                name: Go modules hygine
                run: |
                    go clean -modcache
                    go mod tidy
                working-directory: .
            -
                name: Go test
                run: go test -v ./...
                working-directory: .